---
  deployment:
    tasks: 
        - export DEPLOYPATH=/home/oyebkdud/public_html
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp -R forms $DEPLOYPATH
        - /bin/cp -R docs $DEPLOYPATH
        - /bin/cp -R assets $DEPLOYPATH
