---
  deployment:
    tasks: 
        - export DEPLOYPATH=/home/oyebkdud/vintage-app.oyebolasimeon.cloud/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp -R forms $DEPLOYPATH
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
